name: Plugin asset/readme update
on:
  push:
    branches:
    - main
jobs:
  main:
    name: Push to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: WordPress Plugin Readme/Assets Update
      uses: 10up/action-wordpress-plugin-asset-update@1.4.1
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: woo-for-logged-users
